name: "test"

on: [push]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        compiler: [gcc, clang]
        exclude:
        - os: macos-latest
          compiler: gcc
        - os: windows-latest
          compiler: clang
    runs-on: ${{matrix.os}}
    steps:
    - uses: actions/checkout@master
    - name: Compile
      run: make
    - name: Test
      run: make test

  coverage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: leafo/gh-actions-lua@v8.0.0
    - uses: leafo/gh-actions-luarocks@v4.0.0
    - name: Install luacov
      run: luarocks install luacov && luarocks install cluacov
    - name: Coverage
      run: |
        echo "return {}" > .neluacfg.lua
        make coverage-test

  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: leafo/gh-actions-lua@v8.0.0
    - uses: leafo/gh-actions-luarocks@v4.0.0
    - name: Install luacheck
      run: luarocks install luacheck
    - name: Check
      run: luacheck .
